ADMIN_ = "admin"
GAMBLE_PPC = "gambleppc"
GAMBLE_UAC = "gambleuac"
GAMBLE_FB = "gamblefb"
AFMNGR = "afmngr"
MEDIA_ = "mdeia"
GAMBLE_UAC_PPC = "gambleuac_gambleppc"
TECH_ = "tech"
MT_PARTNERS = "mt_partners"
DESIGNER_ = "designer"


DEP_LIST = (ADMIN_, GAMBLE_FB, GAMBLE_UAC, GAMBLE_UAC_PPC, GAMBLE_PPC, AFMNGR, MEDIA_, TECH_, MT_PARTNERS, DESIGNER_)

DEP_CREO_ACCESS = (ADMIN_, MEDIA_, GAMBLE_FB, GAMBLE_UAC, GAMBLE_PPC, GAMBLE_UAC_PPC)
DEP_TECH_ACCESS = (ADMIN_, GAMBLE_FB, GAMBLE_UAC, GAMBLE_PPC, GAMBLE_UAC_PPC, AFMNGR, MT_PARTNERS)

